// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtfCk8MSgAOmiXXhEUK0HepNM3-0vWs8w',
    appId: '1:828442384435:web:cc5fcc1b8f08f9d9a1ab46',
    messagingSenderId: '828442384435',
    projectId: 'mealmanager-fe659',
    authDomain: 'mealmanager-fe659.firebaseapp.com',
    databaseURL: 'https://mealmanager-fe659-default-rtdb.firebaseio.com',
    storageBucket: 'mealmanager-fe659.firebasestorage.app',
    measurementId: 'G-FB9N32RXHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChgVBTEkU5NbdxCoVs30uySQChOxV1BiY',
    appId: '1:828442384435:android:5f81a74ba52d39ffa1ab46',
    messagingSenderId: '828442384435',
    projectId: 'mealmanager-fe659',
    databaseURL: 'https://mealmanager-fe659-default-rtdb.firebaseio.com',
    storageBucket: 'mealmanager-fe659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuLkDRt9Bq76ddcMFOyznNs52B_OpadEw',
    appId: '1:828442384435:ios:ab846e553461b2c0a1ab46',
    messagingSenderId: '828442384435',
    projectId: 'mealmanager-fe659',
    databaseURL: 'https://mealmanager-fe659-default-rtdb.firebaseio.com',
    storageBucket: 'mealmanager-fe659.firebasestorage.app',
    iosBundleId: 'com.example.mealManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuLkDRt9Bq76ddcMFOyznNs52B_OpadEw',
    appId: '1:828442384435:ios:ab846e553461b2c0a1ab46',
    messagingSenderId: '828442384435',
    projectId: 'mealmanager-fe659',
    databaseURL: 'https://mealmanager-fe659-default-rtdb.firebaseio.com',
    storageBucket: 'mealmanager-fe659.firebasestorage.app',
    iosBundleId: 'com.example.mealManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtfCk8MSgAOmiXXhEUK0HepNM3-0vWs8w',
    appId: '1:828442384435:web:c8536c0d718ce519a1ab46',
    messagingSenderId: '828442384435',
    projectId: 'mealmanager-fe659',
    authDomain: 'mealmanager-fe659.firebaseapp.com',
    databaseURL: 'https://mealmanager-fe659-default-rtdb.firebaseio.com',
    storageBucket: 'mealmanager-fe659.firebasestorage.app',
    measurementId: 'G-SSM2PH2B26',
  );

}